version: "2"
run:
  go: "1.24"
  issues-exit-code: 1
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
  settings:
    dogsled:
      max-blank-identifiers: 3
    errcheck:
      check-type-assertions: false
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 40
    goconst:
      min-len: 2
      min-occurrences: 4
    gocritic:
      disabled-checks:
        - appendAssign
        - commentFormatting
        - commentedOutCode
        - deferInLoop
        - emptyStringTest
        - ifElseChain
        - nestingReduce
        - paramTypeCombine
        - sloppyReassign
        - todoCommentWithoutDetail
        - unnamedResult
        - unnecessaryBlock
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      excludes:
        - G115  # Potential integer overflow when converting between integer types
    nolintlint:
      require-explanation: false
      require-specific: true
    revive:
      rules:
        - name: indent-error-flow
          severity: warning
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - contexts
      - storage/rdb/ent
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - contexts
      - storage/rdb/ent
      - third_party$
      - builtin$
      - examples$
