linters-settings:
  dogsled:
    max-blank-identifiers: 3
  errcheck:
    check-type-assertions: false
  exhaustive:
    default-signifies-exhaustive: true
  goconst:
    min-len: 2
    min-occurrences: 4
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - appendAssign
      - commentFormatting
      - commentedOutCode
      - deferInLoop
      - emptyStringTest
      - ifElseChain
      - nestingReduce
      - paramTypeCombine
      - sloppyReassign
      - todoCommentWithoutDetail
      - unnamedResult
      - unnecessaryBlock
      - whyNoLint
  gosec:
    excludes:
      - G115  # Potential integer overflow when converting between integer types
  govet:
    enable:
      # report about shadowed variables
      - shadowing
  nolintlint:
    require-explanation: false
    require-specific: true
  funlen:
    lines: 100
    statements: 40
  revive:
    rules:
      - name: indent-error-flow
        severity: warning
        disabled: true
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
#    - containedctx
    - contextcheck
    - copyloopvar
#   - depguard
    - dogsled
#   - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
#    - godox
    - gofmt
    - goimports
#   - gomnd
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - testpackage
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign

run:
  issues-exit-code: 1
  go: '1.22'
issues:
  exclude-dirs:
    - contexts
