BEGIN;

CREATE TABLE "accounts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "did" character varying NOT NULL, "state" character varying NOT NULL, "email" character varying NULL, "parent_account" character varying NULL, "body" jsonb NOT NULL, PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "accounts_did_key" ON "accounts" ("did");
CREATE INDEX "account_did" ON "accounts" ("did");
CREATE INDEX "account_state" ON "accounts" ("state");
CREATE INDEX "account_email" ON "accounts" ("email");
CREATE INDEX "account_parent_account" ON "accounts" ("parent_account");
CREATE TABLE "did_documents" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "did" character varying NOT NULL, "body" jsonb NOT NULL, PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "did_documents_did_key" ON "did_documents" ("did");
CREATE UNIQUE INDEX "did_did" ON "did_documents" ("did");
CREATE TABLE "access_keys" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "did" character varying NOT NULL, "body" jsonb NOT NULL, "account" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "access_keys_accounts_access_keys" FOREIGN KEY ("account") REFERENCES "accounts" ("id") ON DELETE SET NULL);
CREATE UNIQUE INDEX "access_keys_did_key" ON "access_keys" ("did");
CREATE UNIQUE INDEX "accesskey_did" ON "access_keys" ("did");
CREATE TABLE "identities" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "hash" character varying NOT NULL, "level" integer NOT NULL, "encrypted_id" character varying NOT NULL, "encrypted_body" character varying NOT NULL, "account" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "identities_accounts_identities" FOREIGN KEY ("account") REFERENCES "accounts" ("id") ON DELETE SET NULL);
CREATE UNIQUE INDEX "identities_hash_key" ON "identities" ("hash");
CREATE UNIQUE INDEX "identity_hash" ON "identities" ("hash");
CREATE TABLE "lockers" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "hash" character varying NOT NULL, "level" integer NOT NULL, "encrypted_id" character varying NOT NULL, "encrypted_body" character varying NOT NULL, "account" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "lockers_accounts_lockers" FOREIGN KEY ("account") REFERENCES "accounts" ("id") ON DELETE SET NULL);
CREATE UNIQUE INDEX "lockers_hash_key" ON "lockers" ("hash");
CREATE UNIQUE INDEX "locker_hash" ON "lockers" ("hash");
CREATE TABLE "properties" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "hash" character varying NOT NULL, "level" integer NOT NULL, "encrypted_id" character varying NOT NULL, "encrypted_body" character varying NOT NULL, "account" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "properties_accounts_properties" FOREIGN KEY ("account") REFERENCES "accounts" ("id") ON DELETE SET NULL);
CREATE UNIQUE INDEX "properties_hash_key" ON "properties" ("hash");
CREATE UNIQUE INDEX "property_hash" ON "properties" ("hash");
CREATE TABLE "recovery_codes" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "code" character varying NOT NULL, "expires_at" timestamptz NULL, "account" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "recovery_codes_accounts_recovery_codes" FOREIGN KEY ("account") REFERENCES "accounts" ("id") ON DELETE SET NULL);
CREATE UNIQUE INDEX "recovery_codes_code_key" ON "recovery_codes" ("code");
CREATE UNIQUE INDEX "recoverycode_code" ON "recovery_codes" ("code");

COMMIT;
